name: گزارش مشکل
description: گزارش مشکل در پلاگین ادیوری
body:

- type: input
  attributes:
    label: نسخه گودو
  validations:
    required: true

- type: input
  attributes:
    label: نسخه پلاگین
  validations:
    required: true

- type: textarea
  attributes:
    label: توضیحات مشکل
  validations:
    required: true

- type: textarea
  attributes:
    label: مراحل
  validations:
    required: true